<?php

namespace Database\Seeders;

use App\Models\Client;
use App\Models\Invoice;
use App\Models\Setting;
use App\Models\User;
use Illuminate\Database\Seeder;

class InvoiceSeeder extends Seeder
{
    public function run(): void
    {
        $clients = Client::all();
        if ($clients->isEmpty()) {
            return;
        }

        $admin = User::where('role', 'owner')->first();
        if (!$admin) {
            $admin = User::first();
        }

        $currency = Setting::get('default_currency', 'USD');
        $taxRate = Setting::get('tax_rate', 0);

        for ($i = 1; $i <= 10; $i++) {
            $client = $clients->random();
            $subTotal = rand(500, 5000);
            $taxTotal = $subTotal * ($taxRate / 100);
            $total = $subTotal + $taxTotal;

            $invoice = Invoice::create([
                'number' => 'INV-' . date('Y') . '-' . str_pad($i, 4, '0', STR_PAD_LEFT),
                'year' => date('Y'),
                'date' => now()->subDays(rand(1, 30)),
                'expired_date' => now()->addDays(rand(1, 30)),
                'client_id' => $client->id,
                'tax_rate' => $taxRate,
                'sub_total' => $subTotal,
                'tax_total' => $taxTotal,
                'total' => $total,
                'currency' => $currency,
                'status' => 'draft',
                'notes' => 'Generated by seeder',
                'created_by' => $admin->id,
            ]);

            // Add items
            for ($j = 1; $j <= rand(2, 5); $j++) {
                $itemPrice = rand(100, 1000);
                $qty = rand(1, 5);
                $invoice->items()->create([
                    'itemName' => 'Service Item ' . $j,
                    'quantity' => $qty,
                    'price' => $itemPrice,
                    'total' => $itemPrice * $qty,
                ]);
            }
        }
    }
}
