<?php

namespace Database\Seeders;

use App\Models\Client;
use App\Models\Proposal;
use App\Models\Setting;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProposalSeeder extends Seeder
{
    public function run(): void
    {
        $clients = Client::all();
        if ($clients->isEmpty()) {
            return;
        }

        $currency = Setting::get('default_currency', 'USD');
        $taxRate = Setting::get('tax_rate', 0);

        for ($i = 1; $i <= 10; $i++) {
            $client = $clients->random();
            $subTotal = rand(500, 5000);
            $taxTotal = $subTotal * ($taxRate / 100);
            $total = $subTotal + $taxTotal;

            $proposal = Proposal::create([
                'number' => 'PROP-' . date('Y') . '-' . str_pad($i, 4, '0', STR_PAD_LEFT),
                'year' => date('Y'),
                'content' => 'Sample proposal content for ' . $client->name,
                'date' => now(),
                'expired_date' => now()->addDays(30),
                'client_id' => $client->id,
                'tax_rate' => $taxRate,
                'sub_total' => $subTotal,
                'tax_total' => $taxTotal,
                'total' => $total,
                'currency' => $currency,
                'status' => 'draft',
                'notes' => 'Generated by seeder',
            ]);

            // Add items
            for ($j = 1; $j <= rand(2, 5); $j++) {
                $itemPrice = rand(100, 1000);
                $qty = rand(1, 5);
                $proposal->items()->create([
                    'itemName' => 'Sample Product ' . $j,
                    'description' => 'Description for product ' . $j,
                    'quantity' => $qty,
                    'price' => $itemPrice,
                    'total' => $itemPrice * $qty,
                ]);
            }
        }
    }
}
